const ITEMS = [
  {name:"Game Boy Color",icon:"🎮",image:"assets/objects/game-boy-color.png",model:"assets/models/game-boy-color.glb",cat:"Rétro gaming",rarity:"peu-commun",min:120,max:240},
  {name:"Cassette collector",icon:"📼",image:"assets/objects/cassette-collector.png",model:"assets/models/cassette-collector.glb",cat:"Rétro gaming",rarity:"sans-rarete",min:18,max:55},
  {name:"Manette vintage",icon:"🕹️",image:"assets/objects/manette-vintage.png",model:"assets/models/manette-vintage.glb",cat:"Rétro gaming",rarity:"courant",min:45,max:95},
  {name:"Montre mécanique",icon:"⌚",image:"assets/objects/montre-mecanique.png",model:"assets/models/montre-mecanique.glb",cat:"Horlogerie",rarity:"peu-commun",min:160,max:380},
  {name:"Réveil années 60",icon:"⏰",image:"assets/objects/reveil-annees-60.png",model:"assets/models/reveil-annees-60.glb",cat:"Horlogerie",rarity:"sans-rarete",min:25,max:75},
  {name:"Chronomètre suisse",icon:"⏱️",image:"assets/objects/chronometre-suisse.png",model:"assets/models/chronometre-suisse.glb",cat:"Horlogerie",rarity:"exceptionnel",min:310,max:620},
  {name:"Appareil argentique",icon:"📷",image:"assets/objects/appareil-argentique.png",model:"assets/models/appareil-argentique.glb",cat:"Photo",rarity:"courant",min:70,max:170},
  {name:"Caméra Super 8",icon:"📹",image:"assets/objects/camera-super-8.png",model:"assets/models/camera-super-8.glb",cat:"Photo",rarity:"peu-commun",min:140,max:330},
  {name:"Objectif japonais",icon:"🔭",image:"assets/objects/objectif-japonais.png",model:"assets/models/objectif-japonais.glb",cat:"Photo",rarity:"rare",min:290,max:710},
  {name:"Vinyle première édition",icon:"💿",image:"assets/objects/vinyle-premiere-edition.png",model:"assets/models/vinyle-premiere-edition.glb",cat:"Musique",rarity:"peu-commun",min:110,max:280},
  {name:"Radio transistor",icon:"📻",image:"assets/objects/radio-transistor.png",model:"assets/models/radio-transistor.glb",nativeModel:"assets/models/radio-transistor-native.glb",cat:"Musique",rarity:"sans-rarete",min:22,max:65},
  {name:"Guitare miniature signée",icon:"🎸",image:"assets/objects/guitare-miniature-signee.png",model:"assets/models/guitare-miniature-signee.glb",cat:"Musique",rarity:"exceptionnel",min:650,max:1300},
  {name:"Lampe de brocante",icon:"🏮",image:"assets/objects/lampe-brocante.png",model:"assets/models/lampe-brocante.glb",cat:"Curiosités",rarity:"sans-rarete",min:15,max:48},
  {name:"Boussole ancienne",icon:"🧭",image:"assets/objects/boussole-ancienne.png",model:"assets/models/boussole-ancienne.glb",cat:"Curiosités",rarity:"courant",min:55,max:125},
  {name:"Masque cérémoniel",icon:"🎭",image:"assets/objects/masque-ceremoniel.png",model:"assets/models/masque-ceremoniel.glb",cat:"Curiosités",rarity:"rare",min:280,max:690},
  {name:"Vase ébréché",icon:"🏺",image:"assets/objects/vase-ebreche.png",model:"assets/models/vase-ebreche.glb",nativeModel:"assets/models/vase-ebreche-hd.glb",true3D:true,cat:"Curiosités",rarity:"sans-rarete",min:12,max:44},
  {name:"Carte sportive",icon:"🃏",image:"assets/objects/carte-sportive.png",model:"assets/models/carte-sportive.glb",cat:"Collections",rarity:"rare",min:90,max:260},
  {name:"Figurine scellée",icon:"🦸",image:"assets/objects/figurine-scellee.png",model:"assets/models/figurine-scellee.glb",cat:"Collections",rarity:"exceptionnel",min:250,max:580},
  {name:"Prototype console n°001",icon:"👾",image:"assets/objects/prototype-console-unique.png",model:"assets/models/prototype-console-unique.glb",cat:"Rétro gaming",rarity:"unique",uniqueKey:"console-001",min:2400,max:4200},
  {name:"Montre de l'Aviateur",icon:"💫",image:"assets/objects/montre-aviateur-unique.png",model:"assets/models/montre-aviateur-unique.glb",cat:"Horlogerie",rarity:"legendaire",uniqueKey:"aviator-watch",min:3800,max:6500},
  {name:"Disque d'or original",icon:"🌟",image:"assets/objects/disque-or-unique.png",model:"assets/models/disque-or-unique.glb",cat:"Musique",rarity:"unique",uniqueKey:"gold-record",min:5000,max:9000}
  ,{name:"Mug cassé Lapin",icon:"☕",image:"assets/objects/mug-casse.png",cat:"Maison",rarity:"sans-rarete",multiplierMin:.2,multiplierMax:.4,min:1,max:25}
  ,{name:"Maillot de foot dédicacé",icon:"👕",image:"assets/objects/maillot-foot-dedicace.png",cat:"Sport",rarity:"unique",uniqueKey:"maillot-10-dedicace",fixedPrice:1998,min:1998,max:1998}
  ,{name:"Magazine de mots-fléchés",icon:"📰",image:"assets/objects/magazine-mots-fleches.png",cat:"Loisir",rarity:"sans-rarete",fixedPrice:9.99,min:9.99,max:9.99}
  ,{name:"Paire de chaussure",icon:"👟",image:"assets/objects/baskets-montantes.png",cat:"Sport",rarity:"legendaire",uniqueKey:"baskets-rouges-blanches",min:500,max:3000}
  ,{name:"Casque de pilote",icon:"🏎️",image:"assets/objects/casque-pilote.png",cat:"Sport",rarity:"unique",uniqueKey:"casque-pilote-jaune",min:3000,max:9000}
  ,{name:"Ciseaux pour gaucher",icon:"✂️",image:"assets/objects/ciseaux-gaucher.png",cat:"Scolaire",rarity:"unique",uniqueKey:"ciseaux-gaucher-rouges",min:1500,max:5000}
  ,{name:"Console rétro",icon:"🎮",image:"assets/objects/console-retro.png",cat:"Loisir",rarity:"rare",min:180,max:650}
  ,{name:"Bocal à Anchois",icon:"🫙",image:"assets/objects/bocal-anchois-vide.png",cat:"Spirituel",rarity:"unique",uniqueKey:"bocal-anchois-vide",min:2000,max:7000}
  ,{name:"Ventilateur",icon:"🌀",image:"assets/objects/ventilateur-2026.png",cat:"Maison",rarity:"legendaire",uniqueKey:"ventilateur-2026",min:700,max:3500}
  ,{name:"BD de l'Homme-Lapin",icon:"📕",image:"assets/objects/bd-homme-lapin.png",cat:"Loisir",rarity:"legendaire",uniqueKey:"bd-homme-lapin-1e",min:900,max:5000}
  ,{name:"Botte d'Astronaute",icon:"🥾",image:"assets/objects/botte-astronaute.png",cat:"Espace",rarity:"unique",uniqueKey:"botte-astronaute-rouge",min:5000,max:15000}
  ,{name:"Un crane de bouc",icon:"🐐",image:"assets/objects/crane-bouc-noir.png",cat:"Spirituel",rarity:"legendaire",uniqueKey:"crane-bouc-noir",fixedPrice:666,min:666,max:666}
  ,{name:"Wilson",icon:"🏐",image:"assets/objects/wilson-volley.png",cat:"Loisir",rarity:"unique",uniqueKey:"wilson-volley",min:3000,max:10000}
  ,{name:"Brosse à dents électrique",icon:"🪥",image:"assets/objects/brosse-dents-electrique.png",cat:"Maison",rarity:"sans-rarete",min:12,max:45}
  ,{name:"Sirop d'érable",icon:"🍁",image:"assets/objects/sirop-erable.png",cat:"Maison",rarity:"sans-rarete",min:8,max:28}
  ,{name:"Mug",icon:"☕",image:"assets/objects/mug-lapin-belier.png",nativeModel:"assets/models/mug-lapin-hd.glb",true3D:true,cat:"Maison",rarity:"sans-rarete",multiplierMin:.4,multiplierMax:.7,min:10,max:35}
  ,{name:"Clé USB 1 To",icon:"💾",image:"assets/objects/cle-usb-1to.png",cat:"Informatique",rarity:"courant",min:45,max:140}
  ,{name:"Barrette de RAM",icon:"🧠",image:"assets/objects/barrette-ram.png",cat:"Informatique",rarity:"exceptionnel",min:240,max:780}
  ,{name:"Portefeuille en cuir",icon:"👛",image:"assets/objects/portefeuille-cuir.png",cat:"Maison",rarity:"peu-commun",min:65,max:190}
  ,{name:"Combinaison de ski",icon:"🎿",image:"assets/objects/combinaison-ski.png",cat:"Loisir",rarity:"peu-commun",min:110,max:320}
  ,{name:"Téléphone à cadran",icon:"☎️",image:"assets/objects/telephone-cadran.png",cat:"Maison",rarity:"rare",min:160,max:480}
  ,{name:"Clé USB 256 Go",icon:"💾",image:"assets/objects/cle-usb-256go.png",cat:"Informatique",rarity:"sans-rarete",min:12,max:42}
  ,{name:"Livre de recettes",icon:"📖",image:"assets/objects/livre-recettes-spaghetti.png",cat:"Maison",rarity:"sans-rarete",min:6,max:25}
  ,{name:"Livre de recettes · Desserts",icon:"🍰",image:"assets/objects/livre-recettes-desserts.png",cat:"Maison",rarity:"sans-rarete",min:6,max:25}
  ,{name:"Cassette vidéo",icon:"📼",image:"assets/objects/cassette-prestigitation.png",cat:"Loisir",rarity:"rare",min:140,max:460}
  ,{name:"Chemisette à fleurs",icon:"👕",image:"assets/objects/chemisette-fleurs.png",cat:"Vêtements",rarity:"sans-rarete",min:8,max:38}
  ,{name:"Chemisette à motifs canards",icon:"🦆",image:"assets/objects/chemisette-canards.png",cat:"Vêtements",rarity:"sans-rarete",min:8,max:38}
  ,{name:"Veste en cuir",icon:"🧥",image:"assets/objects/veste-motard.png",cat:"Vêtements",rarity:"courant",min:80,max:260}
  ,{name:"Grille-pain",icon:"🍞",image:"assets/objects/grille-pain-boite.png",cat:"Maison",rarity:"courant",min:35,max:110}
  ,{name:"Poêle en inox",icon:"🍳",image:"assets/objects/poele-inox.png",cat:"Maison",rarity:"courant",min:45,max:130}
  ,{name:"Carte graphique",icon:"🖥️",image:"assets/objects/carte-graphique.png",cat:"Informatique",rarity:"courant",min:40,max:180}
  ,{name:"Processeur",icon:"🧩",image:"assets/objects/processeur.png",cat:"Informatique",rarity:"courant",min:35,max:220}
  ,{name:"Alimentation PC",icon:"🔌",image:"assets/objects/alimentation-pc.png",cat:"Informatique",rarity:"courant",min:30,max:140}
  ,{name:"Carte mère",icon:"💻",image:"assets/objects/carte-mere.png",cat:"Informatique",rarity:"courant",min:45,max:210}
  ,{name:"Écran PC 1 000 Hz",icon:"🖥️",image:"assets/objects/ecran-pc-1000hz.png",cat:"Informatique",rarity:"courant",min:80,max:350}
  ,{name:"Ventilateur PC",icon:"🌀",image:"assets/objects/ventilateur-pc.png",cat:"Informatique",rarity:"courant",min:12,max:65}
  ,{name:"Nokia 3310 bleu",icon:"📱",image:"assets/objects/nokia-3310.png",cat:"Informatique",rarity:"rare",min:120,max:480}
  ,{name:"Stylo plume marron",icon:"✒️",image:"assets/objects/stylo-plume.png",cat:"Scolaire",rarity:"sans-rarete",min:4,max:28}
  ,{name:"Souris d'ordinateur gaming",icon:"🖱️",image:"assets/objects/souris-gaming.png",cat:"Informatique",rarity:"courant",min:20,max:95}
  ,{name:"Clavier d'ordinateur gaming",icon:"⌨️",image:"assets/objects/clavier-gaming.png",cat:"Informatique",rarity:"courant",min:35,max:150}
  ,{name:"Casque et micro gaming",icon:"🎧",image:"assets/objects/casque-micro-gaming.png",cat:"Informatique",rarity:"courant",min:30,max:140}
  ,{name:"Affiche du film RRRrrrr!!!",icon:"🎬",image:"assets/objects/affiche-rrrrrr.png",cat:"Loisir",rarity:"exceptionnel",min:350,max:1600}
  ,{name:"1 Bitcoin",icon:"🪙",image:"assets/objects/bitcoin.png",cat:"Informatique",rarity:"unique",uniqueKey:"bitcoin-physique",min:3000,max:12000}
  ,{name:"Un serpent venimeux",icon:"🐍",image:"assets/objects/serpent-venimeux.png",cat:"Loisir",rarity:"legendaire",uniqueKey:"serpent-darknet",min:900,max:4200}
  ,{name:"Un sac mortuaire",icon:"⚰️",image:"assets/objects/sac-mortuaire.png",cat:"Loisir",rarity:"courant",min:30,max:140}
  ,{name:"Poster de Tilk dans Stargate",icon:"🌌",image:"assets/objects/poster-tilk.png",cat:"Loisir",rarity:"exceptionnel",min:300,max:1400}
  ,{name:"Télévision cathodique",icon:"📺",image:"assets/objects/television-cathodique.png",cat:"Maison",rarity:"sans-rarete",min:8,max:55}
  ,{name:"Télévision 8K",icon:"📺",image:"assets/objects/television-8k.png",cat:"Maison",rarity:"sans-rarete",min:20,max:90}
  ,{name:"Jeu de société Ça fait 2",icon:"🎲",image:"assets/objects/jeu-ca-fait-2.png",cat:"Loisir",rarity:"exceptionnel",min:280,max:1350}
  ,{name:"Câble RJ45 croisé",icon:"🧵",image:"assets/objects/cable-rj45-croise.png",cat:"Informatique",rarity:"sans-rarete",min:2,max:18}
  ,{name:"Carte ancienne du continent africain",icon:"🗺️",image:"assets/objects/carte-afrique-ancienne.png",cat:"Maison",rarity:"courant",min:35,max:160}
  ,{name:"Maillot de foot d'Auxerre",icon:"👕",image:"assets/objects/maillot-auxerre.png",cat:"Vêtements",rarity:"legendaire",uniqueKey:"maillot-auxerre-retro",min:700,max:4500}
  ,{name:"Un lot de Pogs",icon:"⭕",image:"assets/objects/lot-pogs.png",cat:"Loisir",rarity:"rare",min:130,max:620}
  ,{name:"Ballon de football de 1998",icon:"⚽",image:"assets/objects/ballon-1998.png",cat:"Loisir",rarity:"legendaire",uniqueKey:"ballon-foot-1998",fixedPrice:1998,min:1998,max:1998}
  ,{name:"Panneau entrée de ville · Abbeville",icon:"🪧",image:"assets/objects/panneau-abbeville.png",cat:"Loisir",rarity:"courant",min:45,max:190}
  ,{name:"Cigarette électronique",icon:"💨",image:"assets/objects/cigarette-electronique.png",cat:"Loisir",rarity:"sans-rarete",min:8,max:45}
  ,{name:"Sapin désodorisant",icon:"🌲",image:"assets/objects/sapin-desodorisant.png",cat:"Maison",rarity:"sans-rarete",min:1,max:8}
  ,{name:"Sac de voyage",icon:"🧳",image:"assets/objects/sac-voyage-sandstorm.png",cat:"Maison",rarity:"peu-commun",min:75,max:240}
  ,{name:"Bouteille d'eau SIGNE",icon:"💧",image:"assets/objects/bouteille-eau-signe.png",cat:"Loisir",rarity:"exceptionnel",min:250,max:1300}
  ,{name:"Figurine du chevalier noir",icon:"🗡️",image:"assets/objects/figurine-chevalier-noir.png",cat:"Loisir",rarity:"rare",min:160,max:680}
  ,{name:"Pépite d'or de 72 kg",icon:"🪙",image:"assets/objects/pepite-or-72kg.png",cat:"Loisir",rarity:"unique",uniqueKey:"pepite-or-72kg",min:8000,max:25000}
  ,{name:"Chaussettes France 2018",icon:"🧦",image:"assets/objects/chaussettes-france-2018.png",cat:"Vêtements",rarity:"peu-commun",min:55,max:180}
  ,{name:"Cartable Louison",icon:"🎒",image:"assets/objects/cartable-louison.png",cat:"Vêtements",rarity:"courant",min:25,max:95}
  ,{name:"Roue de secours",icon:"🛞",image:"assets/objects/roue-secours.png",cat:"Maison",rarity:"sans-rarete",min:12,max:55}
  ,{name:"Chemise Safari",icon:"👕",image:"assets/objects/chemise-safari.png",cat:"Vêtements",rarity:"courant",min:30,max:110}
  ,{name:"Spray anti-moustique",icon:"🦟",image:"assets/objects/spray-anti-moustique.png",cat:"Loisir",rarity:"sans-rarete",min:3,max:18}
  ,{name:"Billet pour voyager dans l'espace",icon:"🚀",image:"assets/objects/billet-espace.png",cat:"Loisir",rarity:"legendaire",uniqueKey:"billet-voyage-espace",fixedPrice:500000,min:500000,max:500000}
  ,{name:"DVD Lost · Saison 1",icon:"💿",image:"assets/objects/dvd-the-lost-saison1.png",cat:"Loisir",rarity:"peu-commun",min:45,max:160}
  ,{name:"Miroir cassé",icon:"🪞",image:"assets/objects/miroir-casse.png",cat:"Maison",rarity:"sans-rarete",min:2,max:30}
  ,{name:"Miroir avec contours en or",icon:"🪞",image:"assets/objects/miroir-contours-or.png",cat:"Maison",rarity:"rare",min:180,max:750}
  ,{name:"Pistolet USP",icon:"🔫",image:"assets/objects/pistolet-usp.png",cat:"Loisir",rarity:"courant",min:35,max:140}
  ,{name:"Multiprise",icon:"🔌",image:"assets/objects/multiprise.png",cat:"Maison",rarity:"sans-rarete",min:4,max:25}
  ,{name:"Tournevis",icon:"🪛",image:"assets/objects/tournevis.png",cat:"Maison",rarity:"sans-rarete",min:2,max:18}
  ,{name:"Briquet tempête",icon:"🔥",image:"assets/objects/briquet-tempete.png",cat:"Loisir",rarity:"peu-commun",min:60,max:220}
  ,{name:"Gilet pare-balles",icon:"🦺",image:"assets/objects/gilet-pare-balles.png",cat:"Loisir",rarity:"courant",min:50,max:190}
  ,{name:"Place de concert de Michael Jackson",icon:"🎟️",image:"assets/objects/ticket-concert-michael-jackson.png",cat:"Loisir",rarity:"legendaire",uniqueKey:"ticket-concert-michael-jackson-2009",fixedPrice:2009,min:2009,max:2009}
  ,{name:"Skateboard",icon:"🛹",image:"assets/objects/skateboard.png",cat:"Loisir",rarity:"sans-rarete",min:8,max:55}
  ,{name:"Lunettes connectées",icon:"👓",image:"assets/objects/lunettes-connectees.png",cat:"Loisir",rarity:"peu-commun",min:90,max:320}
  ,{name:"Billet de 500 francs",icon:"💶",image:"assets/objects/billet-500-francs.png",cat:"Loisir",rarity:"exceptionnel",min:350,max:1800}
  ,{name:"Boîte de briques · Retour vers le futur",icon:"🧱",image:"assets/objects/boite-briques-retro-futur.png",cat:"Loisir",rarity:"peu-commun",min:90,max:320}
  ,{name:"Tête de lion empaillée",icon:"🦁",image:"assets/objects/tete-lion-empaillee.png",cat:"Loisir",rarity:"exceptionnel",min:500,max:2400}
  ,{name:"Six bâtons de dynamite",icon:"🧨",image:"assets/objects/dynamite-6.png",cat:"Loisir",rarity:"rare",min:180,max:760}
  ,{name:"Four micro-ondes",icon:"📻",image:"assets/objects/four-micro-ondes.png",cat:"Loisir",rarity:"sans-rarete",min:8,max:60}
  ,{name:"Caquelon",icon:"🫕",image:"assets/objects/caquelon.png",cat:"Maison",rarity:"courant",min:35,max:130}
  ,{name:"Slip de bain Tina Arena",icon:"🩲",image:"assets/objects/slip-bain-tina-arena.png",cat:"Loisir",rarity:"rare",min:170,max:720}
  ,{name:"Robe d’avocat",icon:"⚖️",image:"assets/objects/robe-avocat.png",cat:"Vêtements",rarity:"peu-commun",min:85,max:280}
  ,{name:"Tableau de Claude Monet",icon:"🖼️",image:"assets/objects/tableau-monet.png",cat:"Loisir",rarity:"unique",uniqueKey:"tableau-claude-monet",min:5000,max:22000}
  ,{name:"Kalashnikov Airsoft",icon:"🎯",image:"assets/objects/kalashnikov-airsoft.png",cat:"Loisir",rarity:"peu-commun",min:100,max:380}
  ,{name:"Casse-tête chinois du Japon",icon:"🧩",image:"assets/objects/casse-tete-japonais.png",cat:"Loisir",rarity:"rare",min:140,max:620}
  ,{name:"Vraie dent de requin en plastique",icon:"🦈",image:"assets/objects/dent-requin-plastique.png",cat:"Loisir",rarity:"sans-rarete",min:1,max:15}
  ,{name:"Figurine Ankylosaure",icon:"🦕",image:"assets/objects/figurine-ankylosaure.png",cat:"Loisir",rarity:"courant",collection:"dinosaure",min:25,max:110}
  ,{name:"Figurine de Diplodocus",icon:"🦕",image:"assets/objects/figurine-diplodocus.png",cat:"Loisir",rarity:"courant",collection:"dinosaure",min:25,max:110}
  ,{name:"Figurine d’Aquilops",icon:"🦕",image:"assets/objects/figurine-aquilops.png",cat:"Loisir",rarity:"courant",collection:"dinosaure",min:25,max:110}
  ,{name:"Figurine de Vélociraptor",icon:"🦖",image:"assets/objects/figurine-velociraptor.png",cat:"Loisir",rarity:"courant",collection:"dinosaure",min:25,max:110}
  ,{name:"Figurine de Tricératops",icon:"🦕",image:"assets/objects/figurine-triceratops.png",cat:"Loisir",rarity:"peu-commun",collection:"dinosaure",min:40,max:150}
  ,{name:"Figurine de Stégosaure",icon:"🦕",image:"assets/objects/figurine-stegosaure.png",cat:"Loisir",rarity:"peu-commun",collection:"dinosaure",min:40,max:150}
  ,{name:"Figurine de Ptérodactyle",icon:"🪽",image:"assets/objects/figurine-pterodactyle.png",cat:"Loisir",rarity:"peu-commun",collection:"dinosaure",min:40,max:150}
  ,{name:"Figurine de Brachiosaure",icon:"🦕",image:"assets/objects/figurine-brachiosaure.png",cat:"Loisir",rarity:"rare",collection:"dinosaure",min:90,max:260}
  ,{name:"Figurine de T-Rex",icon:"🦖",image:"assets/objects/figurine-t-rex.png",cat:"Loisir",rarity:"rare",collection:"dinosaure",min:90,max:260}
  ,{name:"Figurine de poulet",icon:"🐔",image:"assets/objects/figurine-poulet-dent.png",cat:"Loisir",rarity:"exceptionnel",collection:"dinosaure",min:250,max:580}
  ,{name:"Taille-crayon pour feutre",icon:"✏️",image:"assets/objects/taille-feutre.png",cat:"Scolaire",rarity:"exceptionnel",min:280,max:1500}
  ,{name:"Bouteille de plongée",icon:"🤿",image:"assets/objects/bouteille-plongee.png",cat:"Loisir",rarity:"courant",min:55,max:210}
  ,{name:"Puzzle 1 pièce",icon:"🧩",image:"assets/objects/puzzle-1-piece.png",cat:"Loisir",rarity:"rare",min:150,max:650}
  ,{name:"Le Saint-Suaire du Christ",icon:"📜",image:"assets/objects/saint-suaire.png",cat:"Vêtements",rarity:"unique",uniqueKey:"saint-suaire-du-christ",fixedPrice:0,min:0,max:0}
];
const UNLIMITED_MONEY=false;
// Les reconstructions IA complètes restent disponibles, mais leur géométrie
// n'est pas assez fidèle. Le rendu principal utilise un relief 3D HD extrudé.
const USE_RECONSTRUCTED_3D=false;
const USE_HD_OBJECT_IMAGES=true;
const PARCEL_IMAGE="assets/boxes/colis-perdu.png";
const PARCEL_MODEL="assets/models/colis-perdu-reference.glb?v=reference2";
const LOT_FORMAT_VERSION=4;
const LOT_TIERS=[{tier:"LOT A",price:[45,55]},{tier:"LOT B",price:[95,105]},{tier:"LOT C",price:[190,210]}];
const PARCEL_ORIGINS=["France","Belgique","Espagne","Italie","Allemagne","Pays-Bas","Portugal","Pologne","Japon","Canada","États-Unis","Royaume-Uni","Corée du Sud","Suède"];
const PARCEL_HUBS=["un centre de tri régional","un entrepôt douanier","une plateforme aéroportuaire","un hub ferroviaire","un dépôt portuaire","un centre de retours","un quai de transit"];
const PARCEL_PLATFORMS=["A****n","E**y","V*****d","A**E******s","C********t","M********e","S****y"];
const RARITIES=[
  {key:"sans-rarete",label:"Sans rareté",chance:40,min:.2,max:.8,color:"#9ca3af"},
  {key:"courant",label:"Courant",chance:30,min:.8,max:1,color:"#f8fafc"},
  {key:"peu-commun",label:"Peu commun",chance:20.89,min:1,max:1.2,color:"#3b82f6"},
  {key:"rare",label:"Rare",chance:6.5,min:1.2,max:1.8,color:"#a855f7"},
  {key:"exceptionnel",label:"Exceptionnel",chance:2.5,min:1.8,max:5,color:"#ef4444"},
  {key:"legendaire",label:"Légendaire",chance:.1,min:5,max:30,color:"#ffd447"},
  {key:"unique",label:"Unique",chance:.01,min:30,max:100,color:"#ff8a1f"}
];
const COLLECTIONS=[
  {key:"dinosaure",name:"Dinosaure",description:"Rassemble les vestiges et objets consacrés aux géants disparus.",badgeKey:"chasseur-dinosaures",badgeName:"Chasseur de dinosaures",badgeIcon:"☠",ready:true,plannedSlots:10}
];
const REPUTATION_LEVELS=[
  {min:0,title:"Nouveau chineur",refresh:50,gift:150,perk:"Accès au dépôt public"},
  {min:10,title:"Chercheur de colis",refresh:45,gift:175,perk:"Renouvellement à 45 $"},
  {min:25,title:"Négociateur",refresh:40,gift:200,perk:"Cadeau quotidien de 200 $"},
  {min:50,title:"Expert du dépôt",refresh:35,gift:250,perk:"Renouvellement à 35 $"},
  {min:100,title:"Roi des cartons",refresh:25,gift:300,perk:"Cadeau quotidien de 300 $"}
];

const SAVE_VERSION=3;
const SAVE_KEY="parcelKingsSave",SAVE_DB="parcelKingsPersistentSave",SAVE_STORE="saves";
const defaultState={saveVersion:SAVE_VERSION,lotFormatVersion:LOT_FORMAT_VERSION,savedAt:0,money:500,xp:0,reputation:0,totalSales:0,cartonsOpened:0,inventory:[],showcase:[],found:[],foundUniques:[],discoveredItems:[],badges:[],lots:[],dailyClaimed:false,dailyDate:null,legendaryDate:null,uniqueDate:null,sound:true};
const freshState=()=>({...defaultState,inventory:[],showcase:[],found:[],foundUniques:[],discoveredItems:[],badges:[],lots:[]});
let state=load(); let selectedLot=null; let revealedItem=null; let modalReturnTab="inventory"; let timerSeconds=240;
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const today=()=>new Date().toISOString().slice(0,10);
if(state.dailyDate!==today())state.dailyClaimed=false;
function hydrateSave(saved){const loaded={...freshState(),...(saved||{}),saveVersion:SAVE_VERSION};if(saved?.lotFormatVersion!==LOT_FORMAT_VERSION){loaded.lots=[];loaded.lotFormatVersion=LOT_FORMAT_VERSION}["inventory","showcase"].forEach(zone=>{loaded[zone]=Array.isArray(loaded[zone])?loaded[zone]:[];loaded[zone]=loaded[zone].map(item=>{const source=ITEMS.find(x=>(x.uniqueKey&&x.uniqueKey===item.uniqueKey)||x.name===item.name);return source?{...item,rarity:source.rarity,...(source.image?{image:source.image}:{}),...(source.model?{model:source.model}:{}),...(source.nativeModel?{nativeModel:source.nativeModel}:{}),...(source.true3D?{true3D:true}:{})}:item})});loaded.badges=Array.isArray(loaded.badges)?loaded.badges:[];const owned=[...loaded.inventory,...loaded.showcase].map(item=>item.name),legacyIcons=Array.isArray(loaded.found)?loaded.found:[],legacyNames=ITEMS.filter(item=>legacyIcons.includes(item.icon)).map(item=>item.name);loaded.discoveredItems=[...new Set([...(Array.isArray(loaded.discoveredItems)?loaded.discoveredItems:[]),...owned,...legacyNames])];return loaded}
function load(){try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY));return saved?hydrateSave(saved):freshState()}catch{return freshState()}}
function openSaveDb(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(new Error("IndexedDB indisponible"));const request=indexedDB.open(SAVE_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(SAVE_STORE))request.result.createObjectStore(SAVE_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function writeBackup(snapshot){try{const db=await openSaveDb(),transaction=db.transaction(SAVE_STORE,"readwrite");transaction.objectStore(SAVE_STORE).put(snapshot,"main");await new Promise((resolve,reject)=>{transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error)});db.close()}catch{}}
async function readBackup(){try{const db=await openSaveDb(),transaction=db.transaction(SAVE_STORE,"readonly"),request=transaction.objectStore(SAVE_STORE).get("main");const result=await new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return result}catch{return null}}
function save(){state.savedAt=Date.now();state.saveVersion=SAVE_VERSION;const snapshot=JSON.parse(JSON.stringify(state));try{localStorage.setItem(SAVE_KEY,JSON.stringify(snapshot))}catch{}writeBackup(snapshot)}
async function initPersistentSave(){try{await navigator.storage?.persist?.()}catch{}const backup=await readBackup(),localTime=Number(state.savedAt)||0,backupTime=Number(backup?.savedAt)||0;if(backup&&backupTime>localTime){state=hydrateSave(backup);if(state.dailyDate!==today())state.dailyClaimed=false;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch{}updateAll();toast("Progression sauvegardée restaurée.")}else if(localTime>0){writeBackup(JSON.parse(JSON.stringify(state)))}else if(localStorage.getItem(SAVE_KEY)){save()}window.addEventListener("pagehide",save,{once:false})}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function randFloat(a,b){return a+Math.random()*(b-a)}
function level(){return Math.floor(state.xp/100)+1}
function money(n){return Number(n).toLocaleString("fr-FR",{minimumFractionDigits:Number.isInteger(Number(n))?0:2,maximumFractionDigits:2})+" $"}
function relief3D(i){
  const layers=Array.from({length:15},(_,n)=>`<img class="relief-layer" style="--depth:${n-7}" src="${i.image}?v=relief1" alt="" draggable="false">`).join("");
  return `<div class="relief-3d" role="img" aria-label="Objet 3D : ${i.name}">${layers}<img class="relief-face" src="${i.image}?v=relief1" alt="${i.name}" draggable="false"><span class="relief-shine"></span></div>`;
}
function objectVisual(i,context="card"){
  const definition=ITEMS.find(x=>x.name===i.name);
  const source=i.nativeModel||definition?.nativeModel;
  const legacy=i.model||definition?.model;
  const native=source||(legacy?`assets/models/native/${legacy.split('/').pop()}`:null);
  const approvedTrue3D=Boolean(i.true3D||definition?.true3D);
  const nativeViewer=()=>{const spin=context==="reveal"?"":"auto-rotate auto-rotate-delay=\"0\" rotation-per-second=\"11deg\"";return `<model-viewer class="true-3d-model native-3d-${context}" src="${native}?v=pbr3" poster="${i.image}" alt="Modèle 3D complet de ${i.name}" camera-controls loading="eager" reveal="auto" ${spin} touch-action="none" interaction-prompt="none" shadow-intensity="1.8" shadow-softness=".88" exposure="1.2" tone-mapping="commerce" environment-image="neutral" camera-orbit="25deg 74deg auto" field-of-view="30deg"></model-viewer>`};
  if(approvedTrue3D&&native)return nativeViewer();
  if(context==="scene"&&i.image)return `<img class="object-image hd-object-image scene-object-image" src="${i.image}?v=showcase2" alt="${i.name}" draggable="false">`;
  if(USE_HD_OBJECT_IMAGES&&i.image)return `<img class="object-image hd-object-image ${context}-object-image" src="${i.image}?v=photo5" alt="${i.name}" draggable="false">`;
  if(native)return nativeViewer();
  if(context==="reveal"&&i.image&&!USE_RECONSTRUCTED_3D)return relief3D(i);
  if(USE_RECONSTRUCTED_3D&&context==="reveal"&&i.model)return `<model-viewer class="true-3d-model" src="${i.model}?v=hq3" poster="${i.image}" alt="Modèle 3D de ${i.name}" camera-controls loading="eager" reveal="auto" touch-action="none" interaction-prompt="none" shadow-intensity="1.4" exposure="1.18" environment-image="neutral" camera-orbit="180deg 90deg auto"></model-viewer>`;
  return i.image?`<img class="object-image ${context}-object-image" src="${i.image}?v=clean1" alt="${i.name}" draggable="false">`:`<span class="emoji-object">${i.icon}</span>`;
}
function beep(freq=420,duration=.08){if(!state.sound)return;try{const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type="triangle";g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+duration)}catch{}}
function premiumSaleSound(){if(!state.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext,a=new Audio(),now=a.currentTime,master=a.createGain(),compressor=a.createDynamicsCompressor();master.gain.setValueAtTime(.0001,now);master.gain.exponentialRampToValueAtTime(.22,now+.012);master.gain.exponentialRampToValueAtTime(.0001,now+1.08);master.connect(compressor);compressor.connect(a.destination);const coin=(frequency,start,duration,volume)=>{const o=a.createOscillator(),harmonic=a.createOscillator(),g=a.createGain();o.type="sine";harmonic.type="triangle";o.frequency.setValueAtTime(frequency,now+start);o.frequency.exponentialRampToValueAtTime(frequency*1.018,now+start+duration);harmonic.frequency.value=frequency*2.76;g.gain.setValueAtTime(.0001,now+start);g.gain.exponentialRampToValueAtTime(volume,now+start+.008);g.gain.exponentialRampToValueAtTime(.0001,now+start+duration);o.connect(g);harmonic.connect(g);g.connect(master);o.start(now+start);harmonic.start(now+start);o.stop(now+start+duration);harmonic.stop(now+start+duration)};coin(987.77,0,.48,.16);coin(1318.51,.095,.56,.13);coin(1567.98,.205,.65,.11);coin(2093,.34,.72,.09);setTimeout(()=>a.close(),1250)}catch{}}
function showcaseSound(open){if(!state.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext,a=new Audio(),now=a.currentTime,master=a.createGain(),filter=a.createBiquadFilter();master.gain.setValueAtTime(.0001,now);master.gain.exponentialRampToValueAtTime(.2,now+.012);master.gain.exponentialRampToValueAtTime(.0001,now+(open?1.25:.82));filter.type="lowpass";filter.frequency.value=open?1250:820;filter.Q.value=.7;filter.connect(master);master.connect(a.destination);const hit=(frequency,start,duration,volume)=>{const o=a.createOscillator(),g=a.createGain();o.type="square";o.frequency.setValueAtTime(frequency,now+start);o.frequency.exponentialRampToValueAtTime(Math.max(32,frequency*.46),now+start+duration);g.gain.setValueAtTime(volume,now+start);g.gain.exponentialRampToValueAtTime(.0001,now+start+duration);o.connect(g);g.connect(filter);o.start(now+start);o.stop(now+start+duration)};const buffer=a.createBuffer(1,Math.floor(a.sampleRate*(open?.82:.48)),a.sampleRate),data=buffer.getChannelData(0);for(let n=0;n<data.length;n++)data[n]=(Math.random()*2-1)*Math.pow(1-n/data.length,2);const noise=a.createBufferSource(),ng=a.createGain();noise.buffer=buffer;ng.gain.setValueAtTime(open?.05:.035,now+.08);ng.gain.exponentialRampToValueAtTime(.0001,now+(open?.9:.55));noise.connect(ng);ng.connect(filter);noise.start(now+.08);hit(open?82:106,0,.18,.18);hit(open?58:74,open?.78:.28,open?.42:.3,.24);if(open){hit(138,.3,.1,.06);hit(164,.47,.1,.05)}}catch{}}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2200)}
function confirmAction({title,message,label="Confirmer",tone="standard"},onConfirm){const backdrop=document.createElement("div");backdrop.className=`confirm-backdrop ${tone}`;backdrop.innerHTML=`<div class="confirm-card" role="alertdialog" aria-modal="true"><span class="confirm-symbol">${tone==="unique"?"◆":tone==="legendaire"?"✦":"!"}</span><p>${tone==="unique"?"DÉCOUVERTE MONDIALE":tone==="legendaire"?"DROP EXCEPTIONNEL":"CONFIRMATION"}</p><h3>${title}</h3><div class="confirm-message">${message}</div><div class="confirm-actions"><button class="secondary" data-confirm-cancel>Annuler</button><button class="primary" data-confirm-ok>${label}</button></div></div>`;document.body.appendChild(backdrop);requestAnimationFrame(()=>backdrop.classList.add("show"));const close=()=>{backdrop.classList.remove("show");setTimeout(()=>backdrop.remove(),180)};backdrop.querySelector("[data-confirm-cancel]").onclick=close;backdrop.querySelector("[data-confirm-ok]").onclick=()=>{close();onConfirm()};backdrop.onclick=e=>{if(e.target===backdrop&&tone==="standard")close()};backdrop.querySelector("[data-confirm-ok]").focus()}
function collectionItems(key){return ITEMS.filter(item=>item.collection===key||(Array.isArray(item.collections)&&item.collections.includes(key)))}
function isDiscovered(item){return state.discoveredItems.includes(item.name)}
function isOwned(item){return [...state.inventory,...state.showcase].some(owned=>(item.uniqueKey&&owned.uniqueKey===item.uniqueKey)||owned.name===item.name)}
function badgeCelebration(collection){const backdrop=document.createElement("div");backdrop.className="badge-award-backdrop";backdrop.innerHTML=`<div class="badge-award-card" role="alertdialog" aria-modal="true"><div class="badge-rays"></div><div class="badge-medallion"><span>${collection.badgeIcon}</span></div><p>NOUVEAU BADGE REMPORTÉ</p><h3>${collection.badgeName}</h3><small>Collection ${collection.name} complétée</small><button class="primary" data-badge-close>Ajouter à mes badges</button></div>${Array.from({length:24},(_,i)=>`<i style="--i:${i}">✦</i>`).join("")}`;document.body.appendChild(backdrop);requestAnimationFrame(()=>backdrop.classList.add("show"));const close=()=>{backdrop.classList.remove("show");setTimeout(()=>backdrop.remove(),250)};backdrop.querySelector("[data-badge-close]").onclick=close;backdrop.onclick=e=>{if(e.target===backdrop)close()};beep(784,.18);setTimeout(()=>beep(1046,.25),130)}
function checkCollectionBadges({silent=false}={}){for(const collection of COLLECTIONS){if(!collection.ready||state.badges.includes(collection.badgeKey))continue;const items=collectionItems(collection.key);if(items.length&&items.every(isOwned)){state.badges.push(collection.badgeKey);save();if(!silent)badgeCelebration(collection)}}}

function parcelStory(){const country=PARCEL_ORIGINS[rand(0,PARCEL_ORIGINS.length-1)],hub=PARCEL_HUBS[rand(0,PARCEL_HUBS.length-1)],platform=PARCEL_PLATFORMS[rand(0,PARCEL_PLATFORMS.length-1)],days=rand(12,240);return {name:`Provenance : ${country}`,desc:`Égaré depuis ${days} jours après son passage par ${hub}. Expédition issue de la plateforme ${platform}.`}}
function createLot(type,id=Date.now()+Math.random()){return {id,tier:type.tier,...parcelStory(),price:rand(...type.price),image:PARCEL_IMAGE}}
function generateLots(){state.lots=LOT_TIERS.map((type,id)=>createLot(type,Date.now()+id));save();renderLots()}
function renderLots(){if(!state.lots.length)generateLots();$("#lots").innerHTML=state.lots.map(l=>`<article class="lot"><div class="lot-visual"><span class="rarity">${l.tier}</span><model-viewer class="parcel-product" src="${PARCEL_MODEL}" poster="${PARCEL_IMAGE}" alt="Carton perdu fermé en rotation" loading="eager" reveal="auto" auto-rotate auto-rotate-delay="0" rotation-per-second="16deg" interaction-prompt="none" camera-orbit="25deg 68deg auto" field-of-view="36deg" shadow-intensity="1.2" environment-image="neutral"></model-viewer><span class="condition">● CONTENU SECRET</span></div><div class="lot-info"><h3>${l.name}</h3><p>${l.desc}</p><div class="lot-footer"><div class="lot-price"><span>Prix du colis</span><b>${money(l.price)}</b></div><button class="primary buy-btn" data-buy="${l.id}" ${state.money<l.price?"disabled":""}>Acheter le colis</button></div></div></article>`).join("");$("#lotCount").textContent=state.lots.length;$$('[data-buy]').forEach(b=>b.onclick=()=>buyLot(Number(b.dataset.buy)))}
function normalizeRarity(r){return ({normal:"sans-rarete",commun:"courant",inhabituel:"peu-commun","épique":"rare","légendaire":"legendaire",legendaire:"legendaire","sans-rarete":"sans-rarete",courant:"courant","peu-commun":"peu-commun",rare:"rare",exceptionnel:"exceptionnel",unique:"unique"})[r]||"sans-rarete"}
function rarityInfo(key){return RARITIES.find(r=>r.key===normalizeRarity(key))||RARITIES[0]}
function reputationLevel(){return [...REPUTATION_LEVELS].reverse().find(level=>state.reputation>=level.min)||REPUTATION_LEVELS[0]}
function nextReputationLevel(){return REPUTATION_LEVELS.find(level=>level.min>state.reputation)}
function rollRarity(){const roll=Math.random()*100;let cursor=0,selected=RARITIES[0];for(const rarity of RARITIES){cursor+=rarity.chance;if(roll<cursor){selected=rarity;break}}if(selected.key==="legendaire"&&state.legendaryDate===today())selected=RARITIES.find(r=>r.key==="exceptionnel");if(selected.key==="unique"&&state.uniqueDate===today())selected=RARITIES.find(r=>r.key==="exceptionnel");return selected}
function pickItem(parcelPrice){const rarity=rollRarity(),tier=ITEMS.filter(x=>normalizeRarity(x.rarity)===rarity.key),base={...tier[rand(0,tier.length-1)]},rolledMultiplier=randFloat(base.multiplierMin??rarity.min,base.multiplierMax??rarity.max);base.rarity=rarity.key;base.rarityLabel=rarity.label;base.id=Date.now()+Math.random();base.parcelPrice=parcelPrice;base.value=base.fixedPrice??Math.max(1,Math.round(parcelPrice*rolledMultiplier));base.multiplier=base.fixedPrice?base.value/parcelPrice:rolledMultiplier;base.boughtAt=Date.now();if(base.rarity==="legendaire")state.legendaryDate=today();if(base.rarity==="unique")state.uniqueDate=today();return base}
function pickTestItem(rarityKey,parcelPrice=100){const rarity=rarityInfo(rarityKey),tier=ITEMS.filter(item=>normalizeRarity(item.rarity)===rarity.key),base={...tier[rand(0,tier.length-1)]},rolledMultiplier=randFloat(base.multiplierMin??rarity.min,base.multiplierMax??rarity.max);base.rarity=rarity.key;base.rarityLabel=rarity.label;base.id=`test-${Date.now()}-${Math.random()}`;base.parcelPrice=parcelPrice;base.value=base.fixedPrice??Math.max(1,Math.round(parcelPrice*rolledMultiplier));base.multiplier=base.fixedPrice?base.value/parcelPrice:rolledMultiplier;base.testPreview=true;return base}
function previewRarity(rarityKey){const rarity=rarityInfo(rarityKey);selectedLot=null;revealedItem=null;modalReturnTab="market";const eyebrow=$("#openingModal>.eyebrow");if(eyebrow)eyebrow.textContent="MODE TEST · AUCUNE CONSERVATION";$("#modalTitle").textContent=`TEST ${rarity.label.toUpperCase()}`;$("#openingStage").classList.remove("hidden");$("#openBox").classList.remove("open");$("#reveal").classList.add("hidden");$("#openAction").textContent="Analyse en cours…";$("#openAction").disabled=true;$("#sellNowAction").hidden=true;$("#modalBackdrop").classList.add("show");beep(250,.1);requestAnimationFrame(()=>$("#openBox").classList.add("open"));setTimeout(()=>{revealedItem=pickTestItem(rarity.key);showItem3D(revealedItem,"Fermer le test");$("#sellNowAction").hidden=true;triggerRarityEffect(revealedItem.rarity);beep(680,.18)},900)}
function buyLot(id){const lot=state.lots.find(l=>l.id===id);if(!lot||state.money<lot.price)return;state.money-=lot.price;const tier=LOT_TIERS.find(x=>x.tier===lot.tier);state.lots=state.lots.map(x=>x.id===id?createLot(tier):x);selectedLot=lot;revealedItem=null;modalReturnTab="inventory";save();updateHeader();renderLots();const eyebrow=$("#openingModal>.eyebrow");if(eyebrow)eyebrow.textContent="OUVERTURE EN COURS";$("#modalTitle").textContent=`${lot.tier} · ${money(lot.price)}`;$("#openingStage").classList.remove("hidden");$("#openBox").classList.remove("open");$("#reveal").classList.add("hidden");$("#openAction").textContent="Ouvrir le colis";$("#openAction").disabled=false;$("#sellNowAction").hidden=true;$("#modalBackdrop").classList.add("show");beep(230,.12)}
function multiplierBadge(item){if(!item.multiplier)return "";const ratio=item.multiplier,kind=ratio>1.001?"profit":ratio<.999?"loss":"neutral",delta=Math.abs(item.value-item.parcelPrice),label=kind==="profit"?"BÉNÉFICE":kind==="loss"?"PERTE":"ÉQUILIBRE",amount=kind==="profit"?`+${money(delta)}`:kind==="loss"?`−${money(delta)}`:"0 $";return `<div class="value-multiplier ${kind}"><span>VALEUR</span><strong>×${ratio.toFixed(2)}</strong><em><small>${label}</small><b>${amount}</b></em></div>`}
function ownedObjectComparison(item){if(!selectedLot)return "";const same=x=>x.id!==item.id&&((item.uniqueKey&&x.uniqueKey===item.uniqueKey)||x.name===item.name),stock=state.inventory.filter(same),displayed=state.showcase.filter(same),owned=[...stock,...displayed];if(!owned.length)return "";const cheapest=owned.reduce((best,current)=>current.value<best.value?current:best),difference=item.value-cheapest.value,comparison=difference>0?`Le nouveau vaut <b class="positive">+${money(difference)}</b> de plus`:difference<0?`Le nouveau vaut <b class="negative">−${money(Math.abs(difference))}</b> de moins`:`Le nouveau a <b>la même valeur</b>`;return `<div class="owned-object-note duplicate"><span>${owned.length+1}×</span><div><strong>DÉJÀ POSSÉDÉ · ${owned.length} EXEMPLAIRE${owned.length>1?"S":""}</strong><small>${stock.length} en stock · ${displayed.length} en vitrine<br>${comparison} que le moins cher déjà possédé (${money(cheapest.value)}).</small></div></div>`}
function showItem3D(item,actionLabel){const rarity=rarityInfo(item.rarity),hasOrigin=item.parcelPrice!=null,delta=hasOrigin?item.value-item.parcelPrice:null,details=`<div class="object-value-details"><span><small>PRIX DU COLIS</small><b>${hasOrigin?money(item.parcelPrice):"Non conservé"}</b></span><i></i><span><small>VALEUR ESTIMÉE</small><b>${money(item.value)}</b></span><i></i><span class="${delta==null?"unknown":delta>=0?"positive":"negative"}"><small>PLUS-VALUE</small><b>${delta==null?"—":`${delta>=0?"+":"−"}${money(Math.abs(delta))}`}</b></span></div>`;const ownership=ownedObjectComparison(item);$("#openingStage").classList.add("hidden");$("#reveal").classList.remove("hidden");$("#reveal").innerHTML=`<div class="reveal-item rarity-${item.rarity}"><div class="object-inspector" id="objectInspector"><div class="inspector-glow"></div><div class="inspector-object">${objectVisual(item,"reveal")}</div></div><p class="rarity-label">${rarity.label.toUpperCase()}</p><h3>${item.name}</h3>${ownership}${details}</div>`;$("#openAction").textContent=actionLabel;$("#openAction").disabled=false;$("#sellNowAction").hidden=!selectedLot;initObjectInspector()}
function triggerRarityEffect(rarity){if(!["legendaire","unique"].includes(rarity))return;const unique=rarity==="unique",burst=document.createElement("div");burst.className=`rarity-burst ${rarity}`;burst.style.setProperty("--burst",unique?"#ff8a1f":"#ffd447");burst.innerHTML=Array.from({length:unique?34:26},(_,i)=>`<span style="--x:${rand(2,98)}%;--y:${rand(20,95)}%;--s:${rand(12,30)}px">${unique?(i%2?"⚡":"◆"):"✦"}</span>`).join("");document.body.appendChild(burst);setTimeout(()=>burst.remove(),3000)}
function inspectStoredItem(id,source){const item=state[source].find(x=>x.id===id);if(!item)return;revealedItem=item;selectedLot=null;modalReturnTab=source;const eyebrow=$("#openingModal>.eyebrow");if(eyebrow)eyebrow.textContent=source==="showcase"?"MA VITRINE":"MON STOCK";$("#modalTitle").textContent=source==="showcase"?"PIÈCE EXPOSÉE":item.name;showItem3D(item,"Fermer");$("#modalBackdrop").classList.add("show")}
function reveal(){if(revealedItem){const cameFromOpening=Boolean(selectedLot);if(cameFromOpening){selectedLot=null;revealedItem=null}closeModal();switchTab(cameFromOpening?"market":modalReturnTab);return}$("#openAction").disabled=true;$("#openBox").classList.add("open");beep(260,.2);setTimeout(()=>{revealedItem=pickItem(selectedLot.price);state.inventory.push(revealedItem);state.found=[...new Set([...state.found,revealedItem.icon])];state.discoveredItems=[...new Set([...state.discoveredItems,revealedItem.name])];state.xp+=25;state.reputation+=2;state.cartonsOpened=(state.cartonsOpened||0)+1;save();const finishReveal=()=>{showItem3D(revealedItem,"Ranger dans mon stock");updateAll();checkCollectionBadges();triggerRarityEffect(revealedItem.rarity);beep(revealedItem.rarity==="unique"?980:revealedItem.rarity==="legendaire"?840:680,.25)};if(["legendaire","unique"].includes(revealedItem.rarity)){const unique=revealedItem.rarity==="unique";confirmAction({title:unique?"Un objet Unique a été trouvé !":"Un objet Légendaire a été trouvé !",message:unique?"Il n’en existe qu’un pour l’ensemble des joueurs aujourd’hui. Confirme pour découvrir cette pièce exceptionnelle.":"Tu viens d’obtenir ton objet légendaire du jour. Confirme pour le révéler.",label:"Découvrir l’objet",tone:revealedItem.rarity},finishReveal)}else finishReveal()},1400)}
const buyLotThenOpen=buyLot;
buyLot=function(id){buyLotThenOpen(id);if(!selectedLot||selectedLot.id!==id||revealedItem)return;$("#openAction").textContent="Ouverture en cours…";$("#openAction").disabled=true;setTimeout(()=>{if(selectedLot&&selectedLot.id===id&&!revealedItem)reveal()},280)};
function initObjectInspector(){const el=$("#objectInspector"),object=el?.querySelector(".inspector-object");if(!el||!object)return;const viewer=el.querySelector("model-viewer");if(viewer){el.classList.add("has-true-3d");const hint=el.querySelector(".drag-hint");if(hint)hint.textContent="↔ MAINTIENS LE CLIC GAUCHE ET DÉPLACE LA SOURIS";let held=false,startX=0,startY=0,yaw=25,pitch=72;const draw=()=>viewer.setAttribute("camera-orbit",`${yaw}deg ${pitch}deg auto`);el.onpointerdown=e=>{if(e.pointerType==="mouse"&&e.button!==0)return;held=true;startX=e.clientX;startY=e.clientY;el.setPointerCapture(e.pointerId);el.classList.add("held");e.preventDefault()};el.onpointermove=e=>{if(!held)return;yaw+=(e.clientX-startX)*.65;pitch=Math.max(20,Math.min(150,pitch+(e.clientY-startY)*.45));startX=e.clientX;startY=e.clientY;draw();e.preventDefault()};const release=e=>{held=false;el.classList.remove("held");if(e.pointerId!==undefined&&el.hasPointerCapture(e.pointerId))el.releasePointerCapture(e.pointerId)};el.onpointerup=release;el.onpointercancel=release;el.onlostpointercapture=()=>{held=false;el.classList.remove("held")};el.oncontextmenu=e=>e.preventDefault();el.onwheel=e=>e.preventDefault();draw();return}let held=false,startX=0,startY=0,rotX=-5,rotY=-12;const draw=()=>{object.style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg) scale(.87)`;el.style.setProperty("--light-x",`${50+rotY*1.1}%`);el.style.setProperty("--light-y",`${45-rotX*1.2}%`)};el.onpointerdown=e=>{held=true;startX=e.clientX;startY=e.clientY;el.setPointerCapture(e.pointerId);el.classList.add("held")};el.onpointermove=e=>{if(!held)return;rotY=Math.max(-48,Math.min(48,rotY+(e.clientX-startX)*.28));rotX=Math.max(-25,Math.min(25,rotX-(e.clientY-startY)*.2));startX=e.clientX;startY=e.clientY;draw()};const release=()=>{held=false;el.classList.remove("held")};el.onpointerup=release;el.onpointercancel=release;draw()}
function closeModal(){$("#modalBackdrop").classList.remove("show")}
function sellItem(id,source="inventory",confirmed=false){const list=state[source],idx=list.findIndex(x=>x.id===id);if(idx<0)return;const item=list[idx];if(source==="showcase"&&!confirmed){confirmAction({title:`Vendre ${item.name} ?`,message:`Cet objet sera retiré de ta vitrine et vendu exactement <strong>${money(item.value)}</strong>. Cette action est définitive.`,label:`Vendre ${money(item.value)}`},()=>sellItem(id,source,true));return}const sale=item.value;list.splice(idx,1);state.money+=sale;state.totalSales+=sale;state.xp+=20;state.reputation+=1;save();updateAll();toast(`${item.name} vendu ${money(sale)} !`);premiumSaleSound()}
function sellRevealedNow(){if(!revealedItem||!selectedLot)return;sellItem(revealedItem.id,"inventory");revealedItem=null;selectedLot=null;closeModal();switchTab("market")}
function moveToShowcase(id){const idx=state.inventory.findIndex(x=>x.id===id);if(idx<0)return;state.showcase.push(state.inventory.splice(idx,1)[0]);save();updateAll();toast("Objet placé dans ta vitrine !");switchTab("showcase")}
function returnToStock(id){const idx=state.showcase.findIndex(x=>x.id===id);if(idx<0)return;state.inventory.push(state.showcase.splice(idx,1)[0]);save();updateAll();toast("Objet retourné dans ton stock.")}
function updateHeader(){const lvl=level(),progress=state.xp%100,rep=reputationLevel(),next=nextReputationLevel();$("#money").textContent=UNLIMITED_MONEY?"∞ $":money(state.money);$("#reputation").textContent=state.reputation+" ★";$("#levelLabel").textContent="Niveau "+lvl;$("#xpLabel").textContent=progress+" / 100 XP";$("#xpBar").style.width=progress+"%";const tooltip=$("#reputationTooltip");if(tooltip)tooltip.innerHTML=`<b>${rep.title}</b><span>${rep.perk}</span><span>Renouvellement : ${money(rep.refresh)}</span><span>Cadeau quotidien : ${money(rep.gift)}</span>${next?`<small>Prochain rang à ${next.min} ★ : ${next.title}</small>`:`<small>Rang maximal atteint</small>`}`;const refresh=$("#refreshBtn small");if(refresh)refresh.textContent=money(rep.refresh)}
function itemCard(i,showcase=false){i.rarity=normalizeRarity(i.rarity);const source=showcase?"showcase":"inventory";return `<article class="item-card rarity-${i.rarity}"><button class="item-icon" data-inspect="${i.id}" data-inspect-source="${source}" aria-label="Agrandir ${i.name}">${objectVisual(i)}<small>${i.rarity}</small><span class="view-3d">HD</span></button><div class="item-info"><h3>${i.name}</h3><div class="item-meta"><span>${i.cat}</span><b>${money(i.value)}</b></div><div class="item-actions">${showcase?`<button class="secondary" data-return="${i.id}">Reprendre</button><button class="primary" data-showcase-sell="${i.id}">Vendre</button>`:`<button class="secondary" data-display="${i.id}">Placer en vitrine</button><button class="primary" data-sell="${i.id}">Vendre</button>`}</div></div></article>`}
function bindInspectButtons(){$$('[data-inspect]').forEach(b=>b.onclick=()=>inspectStoredItem(Number(b.dataset.inspect),b.dataset.inspectSource))}
function renderInventory(){const grid=$("#inventoryGrid"),empty=$("#emptyInventory");empty.style.display=state.inventory.length?"none":"block";grid.innerHTML=state.inventory.map(i=>itemCard(i)).join("");$$('[data-sell]').forEach(b=>b.onclick=()=>sellItem(Number(b.dataset.sell)));$$('[data-display]').forEach(b=>b.onclick=()=>moveToShowcase(Number(b.dataset.display)));bindInspectButtons();$("#inventoryCount").textContent=state.inventory.length;$("#stockValue").textContent=money(state.inventory.reduce((s,i)=>s+i.value,0))}
function renderShowcase(){const grid=$("#showcaseGrid"),empty=$("#emptyShowcase");empty.style.display=state.showcase.length?"none":"block";grid.innerHTML=state.showcase.map(i=>itemCard(i,true)).join("");$$('[data-return]').forEach(b=>b.onclick=()=>returnToStock(Number(b.dataset.return)));$$('[data-showcase-sell]').forEach(b=>b.onclick=()=>sellItem(Number(b.dataset.showcaseSell),"showcase"));bindInspectButtons();$("#showcaseCount").textContent=state.showcase.length;$("#showcaseValue").textContent=money(state.showcase.reduce((s,i)=>s+i.value,0));renderSceneShowcase()}
function renderSceneShowcase(){const scene=$("#sceneShowcase");if(!scene)return;const shown=state.showcase,total=shown.reduce((s,i)=>s+i.value,0);scene.style.setProperty("--showcase-count",shown.length);scene.classList.toggle("gallery-dense",shown.length>6);const title=document.querySelector(".container-showcase-title");if(title)title.textContent="MA VITRINE";const count=$("#showcaseSceneCount"),value=$("#showcaseSceneValue");if(count)count.textContent=shown.length;if(value)value.textContent=money(total);scene.innerHTML=shown.length?shown.map((i,n)=>`<button class="scene-display rarity-${normalizeRarity(i.rarity)}" data-scene-display="${i.id}" style="--slot:${n}" aria-label="Agrandir ${i.name}">${objectVisual(i,"scene")}<small>${i.name}</small><span class="scene-rarity">${rarityInfo(i.rarity).label}</span></button>`).join(""):`<button class="scene-display empty-display" data-empty-display aria-label="Ouvrir ma vitrine"><span>◇</span><small>Vitrine vide</small></button>`;$$('[data-scene-display]').forEach(b=>b.onclick=e=>{e.stopPropagation();inspectStoredItem(Number(b.dataset.sceneDisplay),"showcase")});const emptyBtn=$("[data-empty-display]");if(emptyBtn)emptyBtn.onclick=e=>{e.stopPropagation();switchTab("showcase");toast("Place un objet du stock dans ta vitrine.")}}
function renderCollections(){const root=$("#collectionsGrid");if(!root)return;root.innerHTML=COLLECTIONS.map(collection=>{const items=collectionItems(collection.key),ownedCount=items.filter(isOwned).length,discoveredCount=items.filter(isDiscovered).length,total=Math.max(collection.plannedSlots||0,items.length),futureSlots=Math.max(0,total-items.length),complete=collection.ready&&items.length&&ownedCount===items.length;const slots=items.map(item=>{const discovered=isDiscovered(item),owned=isOwned(item);return `<article class="collection-object ${discovered?"discovered":"hidden-object"} ${owned?"owned":""}"><div class="collection-object-visual">${discovered?`<img src="${item.image}" alt="${item.name}">`:`<span>?</span>`}</div><strong>${discovered?item.name:"Objet non découvert"}</strong><small>${discovered?rarityInfo(item.rarity).label:"???"}</small></article>`}).join("")+Array.from({length:futureSlots},()=>`<article class="collection-object future-object"><div class="collection-object-visual"><span>?</span></div><strong>Objet à venir</strong><small>COLLECTION EN CRÉATION</small></article>`).join("");return `<section class="collection-album ${complete?"complete":""}"><header><div><p>COLLECTION</p><h3>${collection.name}</h3><small>${collection.description}</small></div><div class="collection-progress"><b>${ownedCount}/${total}</b><span>${discoveredCount} découvert${discoveredCount>1?"s":""}</span></div></header><div class="collection-progress-bar"><i style="width:${total?ownedCount/total*100:0}%"></i></div><div class="collection-slots">${slots}</div><footer><div class="mini-badge ${state.badges.includes(collection.badgeKey)?"earned":""}"><span>${collection.badgeIcon}</span><div><small>BADGE</small><b>${collection.badgeName}</b></div></div><em>${collection.ready?(complete?"Collection complétée":"Possède chaque objet pour débloquer le badge"):"Collection en construction · badge bientôt disponible"}</em></footer></section>`}).join("");const count=$("#collectionCount");if(count)count.textContent=COLLECTIONS.length}
function renderBadges(){const root=$("#badgesGrid"),empty=$("#emptyBadges");if(!root)return;const earned=COLLECTIONS.filter(collection=>state.badges.includes(collection.badgeKey));root.innerHTML=earned.map(collection=>`<article class="badge-card"><div class="badge-medallion"><span>${collection.badgeIcon}</span></div><p>COLLECTION ${collection.name.toUpperCase()}</p><h3>${collection.badgeName}</h3><small>Badge définitivement acquis</small></article>`).join("");if(empty)empty.style.display=earned.length?"none":"block";const count=$("#badgeCount");if(count)count.textContent=earned.length}
let activeRanking="sales";
function renderLeaderboard(){const bots=[{n:"MayaDeals",sales:4820,showcase:2760,r:98,a:"🦊"},{n:"LeChineur",sales:3250,showcase:6140,r:76,a:"🧔"},{n:"PixelBroc",sales:2140,showcase:4380,r:61,a:"🤖"},{n:"MamieCash",sales:1380,showcase:7950,r:44,a:"👵"},{n:"CartonMax",sales:740,showcase:1120,r:27,a:"🐻"}],player={n:"Toi",sales:state.totalSales,showcase:state.showcase.reduce((s,i)=>s+i.value,0),r:state.reputation,a:"👑",player:true};const list=[...bots,player].sort((a,b)=>b[activeRanking]-a[activeRanking]);$("#leaderboardList").innerHTML=list.map((x,i)=>`<div class="leader-row ${x.player?"player":""}"><span class="rank">#${i+1}</span><div class="avatar"><i>${x.a}</i><b>${x.n}</b>${activeRanking==="showcase"&&x.player?`<small>${state.showcase.length} objet${state.showcase.length>1?"s":""}</small>`:""}</div><span class="leader-sales">${money(x[activeRanking])}</span><span class="leader-rep">${activeRanking==="sales"?x.r+" réputation":"valeur exposée"}</span></div>`).join("");$("#rankingCaption").textContent=activeRanking==="sales"?"Chiffre d’affaires cumulé de la saison":"Valeur estimée des objets actuellement exposés";$$('[data-ranking]').forEach(b=>b.classList.toggle("active",b.dataset.ranking===activeRanking))}
function renderMoonCounter(){const earthCircumferenceMeters=40075000,cartonHeight=.4,opened=state.cartonsOpened||0,travelled=opened*cartonHeight,remainingKm=Math.max(0,(earthCircumferenceMeters-travelled)/1000),progress=Math.min(100,travelled/earthCircumferenceMeters*100),visibleProgress=opened?Math.max(.8,progress):0;const count=$("#cartonsOpened"),travel=$("#moonTravelled"),percent=$("#moonPercent"),remaining=$("#moonRemaining"),bar=$("#moonProgress"),parcel=$("#moonParcel");if(count)count.textContent=opened.toLocaleString("fr-FR");if(travel)travel.textContent=travelled.toLocaleString("fr-FR",{minimumFractionDigits:Number.isInteger(travelled)?0:1,maximumFractionDigits:1});if(percent)percent.textContent=progress.toLocaleString("fr-FR",{minimumFractionDigits:progress<.01?8:2,maximumFractionDigits:progress<.01?8:2});if(remaining)remaining.textContent=remainingKm.toLocaleString("fr-FR",{maximumFractionDigits:1});if(bar)bar.style.width=`${visibleProgress}%`;if(parcel)parcel.style.left=`${Math.min(97,visibleProgress)}%`}
function updateAll(){updateHeader();renderMoonCounter();renderLots();renderInventory();renderShowcase();renderCollections();renderBadges();renderLeaderboard()}
function switchTab(id){$$('.tabs button').forEach(x=>x.classList.toggle("active",x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle("active",x.id===id));const viewport=$("#garageViewport"),container=$("#container3d");if(viewport&&container){const pinned=id==="showcase";viewport.classList.toggle("showcase-pinned",pinned);if(pinned&&!container.classList.contains("open"))$("#showcaseMark")?.click();if(!pinned&&container.classList.contains("open"))$("#doorLeft")?.click()}if(id==="market")$(".tabs").scrollIntoView({behavior:"smooth"})}

const initObjectInspectorLegacy=initObjectInspector;
initObjectInspector=function(){const el=$("#objectInspector"),viewer=el?.querySelector("model-viewer");if(!el||!viewer)return initObjectInspectorLegacy();el.classList.add("has-true-3d");const hint=el.querySelector(".drag-hint");if(hint)hint.textContent="↔ MAINTIENS LE CLIC GAUCHE ET DÉPLACE LA SOURIS";let held=false,startX=0,startY=0,yaw=180,pitch=90;const draw=()=>viewer.setAttribute("camera-orbit",`${yaw}deg ${pitch}deg auto`);el.onpointerdown=e=>{if(e.pointerType==="mouse"&&e.button!==0)return;held=true;startX=e.clientX;startY=e.clientY;el.setPointerCapture(e.pointerId);el.classList.add("held");e.preventDefault()};el.onpointermove=e=>{if(!held)return;yaw=Math.max(105,Math.min(255,yaw+(e.clientX-startX)*.55));pitch=Math.max(35,Math.min(135,pitch+(e.clientY-startY)*.4));startX=e.clientX;startY=e.clientY;draw();e.preventDefault()};const release=e=>{held=false;el.classList.remove("held");if(e.pointerId!==undefined&&el.hasPointerCapture(e.pointerId))el.releasePointerCapture(e.pointerId)};el.onpointerup=release;el.onpointercancel=release;el.onlostpointercapture=()=>{held=false;el.classList.remove("held")};el.oncontextmenu=e=>e.preventDefault();el.onwheel=e=>e.preventDefault();draw()};

// Contrôleur final : respecte l'orientation frontale déclarée sur le modèle.
initObjectInspector=function(){
  const el=$("#objectInspector"),viewer=el?.querySelector("model-viewer");
  if(!el||!viewer)return initObjectInspectorLegacy();
  el.classList.add("has-true-3d");
  const hint=el.querySelector(".drag-hint");
  if(hint)hint.textContent="↔ MAINTIENS LE CLIC GAUCHE ET DÉPLACE LA SOURIS";
  const orbit=viewer.getAttribute("camera-orbit")||"25deg 74deg auto";
  let held=false,startX=0,startY=0,yaw=parseFloat(orbit)||25,pitch=parseFloat(orbit.split(/\s+/)[1])||74;
  const draw=()=>viewer.setAttribute("camera-orbit",`${yaw}deg ${pitch}deg auto`);
  el.onpointerdown=e=>{if(e.pointerType==="mouse"&&e.button!==0)return;held=true;startX=e.clientX;startY=e.clientY;el.setPointerCapture(e.pointerId);el.classList.add("held");e.preventDefault()};
  el.onpointermove=e=>{if(!held)return;yaw+=(e.clientX-startX)*.55;pitch=Math.max(20,Math.min(150,pitch+(e.clientY-startY)*.4));startX=e.clientX;startY=e.clientY;draw();e.preventDefault()};
  const release=e=>{held=false;el.classList.remove("held");if(e.pointerId!==undefined&&el.hasPointerCapture(e.pointerId))el.releasePointerCapture(e.pointerId)};
  el.onpointerup=release;el.onpointercancel=release;el.onlostpointercapture=()=>{held=false;el.classList.remove("held")};el.oncontextmenu=e=>e.preventDefault();el.onwheel=e=>e.preventDefault();draw();
};

function initGarage3D(){
  const viewport=$("#garageViewport"),scene=$("#garageScene"),container=$("#container3d"),control=$("#containerControl");
  let dragging=false,startX=0,startY=0,rotX=-7,rotY=-7;
  const draw=()=>scene.style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg)`;
  const toggleContainer=()=>{const open=container.classList.toggle("open");viewport.classList.toggle("expanded",open);control.innerHTML=open?"<span>◆</span> Fermer la vitrine":"<span>◆</span> Ouvrir la vitrine";if(open)setTimeout(()=>viewport.scrollIntoView({behavior:"smooth",block:"center"}),120);showcaseSound(open)};
  viewport.classList.add("flat-showcase");control.onclick=toggleContainer;const showcaseMark=$("#showcaseMark");if(showcaseMark)showcaseMark.onclick=e=>{e.stopPropagation();if(!container.classList.contains("open"))toggleContainer()};$("#doorLeft").onclick=toggleContainer;$("#doorRight").onclick=toggleContainer;viewport.addEventListener("mouseleave",()=>{if(container.classList.contains("open")&&!viewport.classList.contains("showcase-pinned"))toggleContainer()});
  viewport.addEventListener("pointerdown",e=>{if((e.pointerType==="mouse"&&e.button!==0)||e.target.closest("button")||viewport.classList.contains("flat-showcase"))return;dragging=true;startX=e.clientX;startY=e.clientY;viewport.setPointerCapture(e.pointerId);viewport.classList.add("dragging")});
  viewport.addEventListener("pointermove",e=>{if(!dragging)return;rotY=Math.max(-28,Math.min(28,rotY+(e.clientX-startX)*.12));rotX=Math.max(-18,Math.min(8,rotX-(e.clientY-startY)*.08));startX=e.clientX;startY=e.clientY;viewport.classList.add("has-moved");draw()});
  const release=()=>{dragging=false;viewport.classList.remove("dragging")};viewport.addEventListener("pointerup",release);viewport.addEventListener("pointercancel",release);viewport.addEventListener("lostpointercapture",release);
}

// Dans la vitrine, un clic simple ouvre l'onglet tandis qu'un clic-glissé
// reste réservé à la rotation native du model-viewer.
function initShowcaseObjectControls(){
  const scene=$("#sceneShowcase");if(!scene)return;
  const bind=()=>scene.querySelectorAll("model-viewer:not([data-direct-drag])").forEach(viewer=>{
    viewer.dataset.directDrag="1";viewer.removeAttribute("camera-controls");viewer.style.pointerEvents="none";
    const surface=document.createElement("span");surface.className="scene-drag-surface";surface.setAttribute("aria-label","Faire tourner l'objet en 3D");viewer.parentElement.appendChild(surface);
    let held=false,moved=false,startX=0,startY=0,yaw=25,pitch=74,resumeTimer=0;
    const draw=()=>viewer.setAttribute("camera-orbit",`${yaw}deg ${pitch}deg auto`);
    surface.addEventListener("pointerdown",e=>{
      if(e.pointerType==="mouse"&&e.button!==0)return;held=true;moved=false;startX=e.clientX;startY=e.clientY;
      const current=(viewer.getAttribute("camera-orbit")||"25deg 74deg").split(/\s+/);yaw=parseFloat(current[0])||25;pitch=parseFloat(current[1])||74;
      clearTimeout(resumeTimer);viewer.removeAttribute("auto-rotate");surface.setPointerCapture(e.pointerId);viewer.classList.add("manual-drag");surface.classList.add("held");e.preventDefault();e.stopPropagation();
    },{passive:false});
    surface.addEventListener("pointermove",e=>{
      if(!held)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.hypot(dx,dy)>1)moved=true;
      yaw+=dx*.75;pitch=Math.max(18,Math.min(155,pitch+dy*.48));startX=e.clientX;startY=e.clientY;draw();e.preventDefault();e.stopPropagation();
    },{passive:false});
    const release=e=>{if(!held)return;held=false;viewer.classList.remove("manual-drag");surface.classList.remove("held");if(surface.hasPointerCapture?.(e.pointerId))surface.releasePointerCapture(e.pointerId);resumeTimer=setTimeout(()=>viewer.setAttribute("auto-rotate",""),700);e.preventDefault();e.stopPropagation()};
    surface.addEventListener("pointerup",release,{passive:false});surface.addEventListener("pointercancel",release,{passive:false});
    surface.addEventListener("click",e=>{if(!moved)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();moved=false},true);
  });
  bind();new MutationObserver(bind).observe(scene,{childList:true,subtree:true});
}

$$('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go));$$('[data-test-rarity]').forEach(b=>b.onclick=()=>previewRarity(b.dataset.testRarity));$("#scrollToLots").onclick=()=>$(".tabs").scrollIntoView({behavior:"smooth"});$("#openAction").onclick=reveal;$("#closeModal").onclick=closeModal;$("#modalBackdrop").onclick=e=>{if(e.target===$("#modalBackdrop"))closeModal()};$("#refreshBtn").onclick=()=>{if(state.money<50)return toast("Il te faut 50 € pour renouveler.");state.money-=50;generateLots();updateHeader();toast("Le camion vient d'arriver !")};$("#dailyBtn").onclick=()=>{if(state.dailyClaimed)return toast("Reviens demain pour un nouveau cadeau.");state.money+=150;state.dailyClaimed=true;state.dailyDate=today();save();updateHeader();$("#giftDot").style.display="none";toast("Cadeau récupéré : +150 € !");beep(880,.2)};$("#soundBtn").onclick=()=>{state.sound=!state.sound;save();$("#soundBtn").textContent=state.sound?"♪":"×";toast(state.sound?"Son activé":"Son coupé")};
$("#refreshBtn").onclick=()=>{const cost=reputationLevel().refresh;if(state.money<cost)return toast(`Il te faut ${money(cost)} pour renouveler.`);state.money-=cost;generateLots();updateHeader();toast(`${reputationLevel().title} : nouvel arrivage pour ${money(cost)} !`)};
$("#dailyBtn").onclick=()=>{if(state.dailyClaimed)return toast("Reviens demain pour un nouveau cadeau.");const reward=reputationLevel().gift;state.money+=reward;state.dailyClaimed=true;state.dailyDate=today();save();updateHeader();$("#giftDot").style.display="none";toast(`Bonus ${reputationLevel().title} : +${money(reward)} !`);beep(880,.2)};
$("#addCreditsBtn").onclick=()=>{state.money+=1000;save();updateHeader();renderLots();toast("Crédits de test ajoutés : +1 000 $ !");beep(920,.16)};
$("#sellNowAction").onclick=sellRevealedNow;
$$('[data-ranking]').forEach(b=>b.onclick=()=>{activeRanking=b.dataset.ranking;renderLeaderboard();beep(430,.06)});
setInterval(()=>{timerSeconds--;if(timerSeconds<0){timerSeconds=240;generateLots();toast("Nouvel arrivage au dépôt !")}const m=String(Math.floor(timerSeconds/60)).padStart(2,"0"),s=String(timerSeconds%60).padStart(2,"0");$("#timer").textContent=`${m}:${s}`},1000);
if(state.dailyClaimed)$("#giftDot").style.display="none";$("#soundBtn").textContent=state.sound?"♪":"×";updateAll();initGarage3D();initPersistentSave();
